import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AdminService, AdminStats, AdminTransaction, AdminUser, AuditEntry, PayoutFailure, MissingPayout, ReconciliationEntry } from '../../services/admin';
import { AdminPdfService, PdfColumn } from '../../services/admin-pdf';
import { SystemFailureLog, SystemFailuresService } from '../../services/system-failures';
import { AuthService } from '../../services/auth';

@Component({ selector:'app-admin-reports', standalone:true, imports:[CommonModule], templateUrl:'./admin-reports.html' })
export class AdminReports implements OnInit {
  private svc=inject(AdminService); private failureSvc=inject(SystemFailuresService); private pdf=inject(AdminPdfService); private auth=inject(AuthService);
  loading=signal(false); error=signal(''); stats=signal<AdminStats|null>(null); transactions=signal<AdminTransaction[]>([]); users=signal<AdminUser[]>([]); audit=signal<AuditEntry[]>([]); payouts=signal<PayoutFailure[]>([]); missingPayouts=signal<MissingPayout[]>([]); reconciliation=signal<ReconciliationEntry[]>([]); failures=signal<SystemFailureLog[]>([]);
  ngOnInit(){if(!this.auth.getCachedToken()||!this.auth.isAdmin()){window.location.href='/admin';return;}this.load();}
  load(){this.loading.set(true);this.error.set('');let completed=0;const done=()=>{completed++;if(completed===8)this.loading.set(false)};const failed=()=>{this.error.set('One or more report datasets could not be loaded.');done()};
    this.svc.getStats().subscribe({next:x=>{this.stats.set(x);done()},error:failed});this.svc.getTransactions({page:1,size:100}).subscribe({next:x=>{this.transactions.set(x.items);done()},error:failed});this.svc.getUsers({page:1,size:100}).subscribe({next:x=>{this.users.set(x.items);done()},error:failed});this.svc.getAuditLog({page:1,size:100}).subscribe({next:x=>{this.audit.set(x.items);done()},error:failed});this.svc.getPayoutFailures({page:1,size:100}).subscribe({next:x=>{this.payouts.set(x.items);done()},error:failed});this.svc.getMissingPayouts().subscribe({next:x=>{this.missingPayouts.set(x);done()},error:failed});this.svc.getReconciliation({page:1,size:100}).subscribe({next:x=>{this.reconciliation.set(x.items);done()},error:failed});this.failureSvc.get({page:1,size:100,resolved:''}).subscribe({next:x=>{this.failures.set(x.items);done()},error:failed});}
  back(){window.location.href='/admin';}
  downloadStatsPdf(){const s=this.stats();if(!s)return;this.pdf.downloadSummary('Operations Summary',[{label:'Fees Collected',value:this.money(s.totalFeesCollected),accent:'blue'},{label:'Funds in Escrow',value:this.money(s.fundsInEscrow),accent:'green'},{label:'Open Disputes',value:String(s.openDisputes),accent:'red'},{label:'Pending Payouts',value:String(s.pendingPayouts),accent:'amber'},{label:'Total Users',value:String(s.totalUsers),accent:'slate'}],[{title:'Transactions by Status',rows:s.transactionsByStatus.map(x=>[x.status,String(x.count)])}], 'securex-operations-summary.pdf');}
  downloadTransactionsPdf(){const columns:PdfColumn[]=[{label:'Reference',width:105},{label:'Item',width:125},{label:'Seller',width:100},{label:'Buyer',width:100},{label:'Value',width:70,align:'right'},{label:'Fee',width:65,align:'right'},{label:'Status',width:80},{label:'Created',width:100}];const rows=this.transactions().map(x=>[x.dealReference,x.itemTitle,x.seller?.email||'—',x.buyer?.email||'—',this.money(x.itemValue),this.money(x.platformFee),x.status,this.date(x.createdAt)]);this.pdf.downloadTable('Transaction Report',columns,rows,'securex-transactions-report.pdf');}
  downloadUsersPdf(){const columns:PdfColumn[]=[{label:'Name',width:110},{label:'Email',width:160},{label:'ID Check',width:75},{label:'AML',width:65},{label:'Liveness',width:75},{label:'Bank',width:100},{label:'Suspended',width:70},{label:'Created',width:100}];const rows=this.users().map(x=>[x.fullName,x.email,x.idCheckStatus,x.amlStatus,x.livenessStatus,x.bankVerificationStatus,x.isSuspended?'Yes':'No',this.date(x.createdAt)]);this.pdf.downloadTable('Users & Compliance Report',columns,rows,'securex-users-compliance-report.pdf');}
  downloadAuditPdf(){const columns:PdfColumn[]=[{label:'Timestamp',width:105},{label:'Actor',width:95},{label:'Transaction',width:115},{label:'Previous',width:95},{label:'New Status',width:95},{label:'Details',width:250}];const rows=this.audit().map(x=>[this.date(x.timestamp),x.triggerActor,x.transactionId||'—',x.previousStatus||'—',x.newStatus,x.actionDetails]);this.pdf.downloadTable('Audit Log Report',columns,rows,'securex-audit-report.pdf');}
  downloadPayoutPdf(){const columns:PdfColumn[]=[{label:'Type',width:65},{label:'Payout / Deal',width:125},{label:'Reference',width:120},{label:'Status',width:65},{label:'Amount',width:75,align:'right'},{label:'Reason / Verification',width:210},{label:'Created',width:100}];const rows:string[][]=[];this.payouts().forEach(x=>rows.push(['Failure',x.payoutId,x.merchantReference||'—',String(x.status),'—',(x.reason||'No reason')+' / sub '+(x.subStatus??'—'),this.date(x.createdAt)]));this.missingPayouts().forEach(x=>rows.push(['Missing',x.dealReference,x.sellerEmail||'—','Missing',this.money(x.sellerPayout),'KYC '+(x.sellerKycComplete?'complete':'incomplete')+' / Bank '+(x.sellerHasBank?'available':'missing'),'—']));this.pdf.downloadTable('Payout Operations Report',columns,rows.length?rows:[['—','No exceptions','—','—','—','No payout exceptions returned','—']],'securex-payout-report.pdf');}
  downloadReconciliationPdf(){const columns:PdfColumn[]=[{label:'Run At',width:120},{label:'Expected Float',width:135,align:'right'},{label:'Ozow Float',width:135,align:'right'},{label:'Discrepancy',width:135,align:'right'},{label:'Alert',width:100}];const rows=this.reconciliation().map(x=>[this.date(x.runAt),this.money(x.expectedFloat),this.money(x.ozowFloat),this.money(x.discrepancy),x.alertFired?'Alert Fired':'OK']);this.pdf.downloadTable('Reconciliation Report',columns,rows.length?rows:[['—','R 0.00','R 0.00','R 0.00','No records']],'securex-reconciliation-report.pdf');}
  downloadFailuresPdf(){const columns:PdfColumn[]=[{label:'Time',width:85},{label:'Severity',width:70},{label:'Service',width:85},{label:'Endpoint',width:140},{label:'HTTP',width:45,align:'center'},{label:'Category',width:85},{label:'Transaction',width:100},{label:'Occurrences',width:70,align:'center'},{label:'Status',width:65},{label:'Message',width:130}];const rows=this.failures().map(x=>[this.date(x.createdAt),x.severity,x.service,x.method+' '+x.path,String(x.statusCode),x.category,x.transactionId||'—',String(x.occurrenceCount),x.resolved?'Resolved':'Open',x.message]);this.pdf.downloadTable('System Failure Incident Report',columns,rows.length?rows:[['—','—','—','—','—','—','—','0','None','No system failure records returned']],'securex-system-failures-report.pdf');}
  downloadCsv(type:string){let header='';let rows:string[]=[];if(type==='transactions'){header='Reference,Item,Seller,Buyer,Value,Fee,Status,Created';rows=this.transactions().map(x=>[x.dealReference,x.itemTitle,x.seller?.email,x.buyer?.email,x.itemValue,x.platformFee,x.status,x.createdAt].map(this.csv).join(','));}else if(type==='users'){header='Name,Email,ID Check,AML,Liveness,Bank,Suspended,Created';rows=this.users().map(x=>[x.fullName,x.email,x.idCheckStatus,x.amlStatus,x.livenessStatus,x.bankVerificationStatus,x.isSuspended,x.createdAt].map(this.csv).join(','));}else if(type==='audit'){header='Timestamp,Actor,Transaction,Previous Status,New Status,Details';rows=this.audit().map(x=>[x.timestamp,x.triggerActor,x.transactionId,x.previousStatus,x.newStatus,x.actionDetails].map(this.csv).join(','));}else return;this.downloadText(header+'\n'+rows.join('\n'),`securex-${type}-report.csv`,'text/csv;charset=utf-8');}
  private csv(value:unknown){return '"'+String(value??'').replace(/"/g,'""')+'"';}
  private money(value:number){return 'R '+Number(value||0).toFixed(2);}
  private date(value:string){return value?new Date(value).toLocaleString('en-ZA',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—';}
  private downloadText(text:string,name:string,type:string){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
}